# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
- name: L1AssetRouter
  handler: src/EventHandlers.ts
  events:
  - event: BridgehubDepositBaseTokenInitiated(uint256 indexed chainId, address indexed from, bytes32 assetId, uint256 amount)
  - event: BridgehubDepositFinalized(uint256 indexed chainId, bytes32 indexed txDataHash, bytes32 indexed l2DepositTxHash)
  - event: BridgehubDepositInitiated(uint256 indexed chainId, bytes32 indexed txDataHash, address indexed from, bytes32 assetId, bytes bridgeMintCalldata)
  - event: ClaimedFailedDepositAssetRouter(uint256 indexed chainId, bytes32 indexed assetId, bytes assetData)
  - event: DepositFinalizedAssetRouter(uint256 indexed chainId, bytes32 indexed assetId, bytes assetData)
  - event: LegacyDepositInitiated(uint256 indexed chainId, bytes32 indexed l2DepositTxHash, address indexed from, address to, address l1Token, uint256 amount)
networks:
- id: 1
  start_block: 23006299
  contracts:
  - name: L1AssetRouter
    address:
    - 0x8829AD80E425C646DAB305381ff105169FeEcE56
- id: 324
  start_block: 63394479
  contracts:
  - name: L1AssetRouter
    address:
    - '0x0000000000000000000000000000000000010003'
unordered_multichain_mode: true
