# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 8453
  start_block: 0
  contracts:
  - name: TokenMessenger
    address:
    - 0x1682Ae6375C4E4A97e4B583BC394c861A46D8962
    handler: src/EventHandlers.ts
    events:
    - event: DepositForBurn(uint64 indexed nonce, address indexed burnToken, uint256 amount, address indexed depositor, bytes32 mintRecipient, uint32 destinationDomain, bytes32 destinationTokenMessenger, bytes32 destinationCaller)
  - name: MessageTransmitter
    address:
    - 0xAD09780d193884d503182aD4588450C416D6F9D4
    handler: src/EventHandlers.ts
    events:
    - event: MessageReceived(address indexed caller, uint32 sourceDomain, uint64 indexed nonce, bytes32 sender, bytes messageBody)
unordered_multichain_mode: true
